label tavern_story:
    hide cass_img with moveoutbottom
    "Gdy już miałem zamiar się podnieść, pewien już całkiem podchmielony bywalec tawerny trzasnął dłonią o stół i wstał."
    "Cała sala od razu zwróciła na niego uwagę, ciekawa, co dalej się wydarzy."
    "Mężczyzna w już znaczącym wieku i z wyszczerbioną szczęką rzucał słowami na lewo i prawo. Ludzie zebrali się wokół niego, tworząc ciasny krąg."
    oldman "Mówię wam! Tam się dzieją rzeczy, o których w życiu wam się nie śniło!"
    audience "Tak, tak. Gadaj sobie staruszku…"
    oldman "Klnę się na swoje towary, że nie zmyślam! Słyszałem nawet krążącą legendę, która mówi, że korzystają z pradawnego artefaktu… a teraz jej wysłuchajcie."
    oldman_nvl "Nie tak daleko stąd, za lasem,"
    oldman_nvl "Bagno kryje się pod czasem."
    oldman_nvl "Mroczne, pełne tajemnicy,"
    oldman_nvl "Gdzie spokoju nikt nie liczy."
    oldman_nvl "Ludzie w ruinach swe dni pędzą,"
    oldman_nvl "W cieniu strachu życie wstrętne."
    oldman_nvl "Nieznane istoty wciąż krążą,"
    oldman_nvl "Jak sępy nad miastem się wciąż zmożą."
    oldman_nvl "Nikt nie śmie z kryjówki wyjść,"
    oldman_nvl "Bo z bagien złe moce chcą ich gryźć."
    oldman_nvl "Lecz broń ukryta w rękach szamanów,"
    oldman_nvl "Chroni przed zgubą tych z bagien szatanów."
    oldman_nvl "Artefakt ze starego świata,"
    oldman_nvl "Zło odpędza, gdy mrok ich oplata."
    audience "Czyżby mówił prawdę?"
    audience "Ale to w takim razie o jaki artefakt chodzi?!"
    audience "Czy można go zdobyć?"
    audience "Staruszku, no powiedz wreszcie, o jaki artefakt chodzi?"
    oldman "Już spokojnie, wiem, wiem. Jak tak bardzo chcecie, to powiem. Mówi się, że artefakt ten to..."
    oldman "(rzyg)"
    "Staruszek zatoczył się z powrotem na krzesło i zasnął pijackim snem."
    cass "Dobra, rozejść się! Nie ma już żadnego przedstawienia, proszę nie robić mi tutaj rozróby!"
    "Tłum, zawiedziony i zniechęcony przez właścicielkę, rozrzedza się i jedynie nieliczni pozostali w obrębie stołu, rozmawiając ze sobą o przemowie starca."
    "Pierwszy raz w życiu słyszałem o takiej legendzie. Nie jestem pewny, czy aby nie były to jedynie majaki pijanego staruszka, ale warto popytać się ludzi obok, czy może sami czegoś na ten temat nie wiedzą."